version: "3.1"
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    networks:
      - airflow

  # Serviço para criar os buckets automaticamente
  create-buckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - airflow
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local_minio http://minio:9000 admin password) do echo 'Aguardando MinIO...' && sleep 1; done;
      /usr/bin/mc mb local_minio/bronze-layer --ignore-existing;
      /usr/bin/mc mb local_minio/silver-layer --ignore-existing;
      /usr/bin/mc mb local_minio/gold-layer --ignore-existing;
      exit 0;
      "
  # --- QUERY ENGINE (SQL) ---
  trino:
    image: trinodb/trino:latest
    container_name: trino_server
    ports:
      - "8089:8080" # 8089 no seu PC -> 8080 interna (evita conflito com Airflow)
    volumes:
      - ./include/trino/catalog:/etc/trino/catalog
    networks:
      - airflow
    deploy:
      resources:
        limits:
          memory: 2G

  # --- VISUALIZATION (BI) ---
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_ui
    depends_on:
      - trino
    ports:
      - "3000:3000"
    networks:
      - airflow

