[pytest]
# Adiciona a raiz do projeto e a pasta dags ao caminho de busca do Python
pythonpath = . dags

# Define onde o pytest deve procurar pelos testes
testpaths = tests

# Configurações de exibição (opcional, mas recomendado)
addopts = -v --tb=short --cov=dags --cov-report=term-missing --cov-report=html

# Padrões de nome de arquivo para testes
python_files = test_*.py
python_classes = Test*
python_functions = test_*
